name: Deploy app and infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy infrastructure with CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/template.yml \
            --stack-name photo-album-stack1 \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              ProjectName=photo-album \
              EnvironmentName=prod \
              DBUsername=${{ secrets.DB_USERNAME }} \
              DBPassword=${{ secrets.DB_PASSWORD }} \
              AppSecretKey=${{ secrets.FLASK_SECRET_KEY }}
              ApplicationHealthCheckPath=/health \
              ExistingOrNewBucketName=e14kqr-photo-album-bucket-v17

      - name: Package application
        run: |
          zip -r deploy.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x ".venv/*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x ".env" \
            -x "infrastructure/*"


      - name: Show package content
        run: unzip -l deploy.zip | head -100

      - name: Deploy app to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: photo-album-prod-app-v17
          environment_name: photo-album-prod-env-v17
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          wait_for_deployment: true